project:
  type: website

website:
  title: "Lampe30"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - image-class.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
